name: main

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  id-token: write
  packages: write

env:
    REGISTRY: ghcr.io

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout Repositoy
              uses: actions/checkout@v4

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: |
                    ghcr.io/${{ github.repository_owner }}/coprocessor-solver
                tags: |
                      type=semver,pattern={{version}}
                      type=ref,event=pr
                      type=raw,value=testing,enable=${{ github.ref == format('refs/heads/{0}', 'testing') }}
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

                labels: |
                        org.opencontainers.image.title=Coprocessor Solver
                        org.opencontainers.image.description=Coprocessor Solver
            
            - name : Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Github Container Registry (GHCR)
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Setup Depot ClI
              uses: depot/setup-action@v1
              
            - name: Build and push (depot)
              uses: depot/bake-action@v1
              with:
                    project: ${{ vars.DEPOT_PROJECT }}
                    files: |
                        ./docker-bake.hcl
                        ./docker-bake.platforms.hcl
                        ${{ steps.meta.outputs.bake-file }}
                    push: true
